apiVersion: v1
kind: Service
metadata:
  labels:
    app: bar
    service: bar
  name: bar
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: bar
