apiVersion: apps/v1
kind: Deployment
metadata:
  name: baz
  labels:
    app: baz
    version: v1
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: baz
      version: v1
  template:
    metadata:
      labels:
        app: baz
        version: v1
    spec:
      containers:
        - name: baz
          image: gashirar/sak-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: static/liveness.html
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: static/readiness.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 120
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VERSION
              value: "v3"
#            - name: BACKEND_SERVICE
#              value: "http://bar:8080/backend"
            - name: DELAY_RESPONSE_MSEC
              value: "0"
            - name: DELAY_RESPONSE_PERCENTAGE
              value: "0"
            - name: RANDOM_DELAY
              value: "0"
            - name: FAULT_RESPONSE_PERCENTAGE
              value: "0"
