apiVersion: v1
kind: Service
metadata:
  labels:
    app: corge
    service: corge
  name: corge
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: corge
