apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
    service: foo
  name: foo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: foo
