apiVersion: v1
kind: Service
metadata:
  labels:
    app: quux
    service: quux
  name: quux
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: quux
