apiVersion: v1
kind: Service
metadata:
  labels:
    app: qux
    service: qux
  name: qux
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: qux
